language: c
os:
    - linux
    - osx
compiler:
    - gcc
    - clang
arch:
    - amd64
    - ppc64le
    - s390x
    - arm64
env:
    - ARCH="-m64"
    - ARCH="-m32"

jobs:
    exclude:
        - os: osx
          arch: ppc64le
        - os: osx
          arch: s390x
        - os: osx
          arch: arm64

addons:
    apt:
        packages:
            - gcc-multilib

sudo: required
dist: trusty

script: make ARCH=${ARCH} test
