language: c
os:
    - linux
    - osx
dist: xenial
compiler:
    - gcc
    - clang
arch:
    - amd64
    - ppc64le   # apt-get can't find multilib for this arch
    - arm64     # apt-get can't find multilib for this arch
    # - s390x     Build fails. Don't have hardware to debug on.
env:
    - ARCH="-m64"
    - ARCH="-m32"

jobs:
    exclude:
        - os: osx
          arch: ppc64le
        - os: osx
          arch: s390x
        - os: osx
          arch: arm64
    include:
        - os: windows
          compiler: mingw
          env: ARCH="-m64"
        - os: windows
          compiler: mingw
          env: ARCH="-m32"
        - os: windows
          compiler: clang
          env: ARCH="-m64"
        - os: windows
          compiler: clang
          env: ARCH="-m32"

install:
    if [ $ARCH = -m32 ]; then sudo apt-get install gcc-multilib; fi

script: make CC=${CC} ARCH=${ARCH} test
