language: c
os:
    - linux
    - osx
    - windows
dist: xenial
compiler:
    - gcc
    - clang
arch:
    - amd64
    - ppc64le
    # - s390x     Build fails. Don't have hardware to debug on.
env:
    - ARCH="-m64"
    - ARCH="-m32"

jobs:
    exclude:
        - os: osx
          arch: ppc64le
        - os: windows
          arch: ppc64le
        - os: windows
          compiler: gcc
        - compiler: gcc
          arch: ppc64le
          env: ARCH="-m32"
    include:
        - os: windows
          compiler: mingw
          env: ARCH="-m64"
        - os: windows
          compiler: mingw
          env: ARCH="-m32"
        - arch: arm64
          os: linux
          compiler: gcc
          env:
        - arch: arm64
          os: linux
          compiler: clang
          env:

install:
    - if [ $TRAVIS_OS_NAME = windows ]; then
        choco install make;
      elif [ "$ARCH" = -m32 ] && [ $TRAVIS_CPU_ARCH = amd64 ] ; then
        sudo apt-get install gcc-multilib;
      fi

script: make CC=${CC} ARCH=${ARCH} test
