language: c
os:
    - linux
    - osx
compiler:
    - gcc
    - clang
env:
    - ARCH="-m64"
    - ARCH="-m32"

jobs:
    allow_failures:
        - os: osx
          env: ARCH="-m64"

addons:
    apt:
        packages:
            - gcc-multilib

sudo: required
dist: trusty

script: make ARCH=${ARCH} test
