language: c
os:
    - linux
    - osx
compiler:
    - gcc
    - clang
arch:
    - amd64
      # - ppc64le   apt-get can't find multilib for this arch
      # - arm64     apt-get can't find multilib for this arch
      # - s390x     Build fails. Don't have hardware to debug on.
env:
    - ARCH="-m64"
    - ARCH="-m32"

jobs:
    exclude:
        - os: osx
          arch: ppc64le
        - os: osx
          arch: s390x
        - os: osx
          arch: arm64

addons:
    apt:
        packages:
            - gcc-multilib

script: make CC=${CC} ARCH=${ARCH} test
